version: '3.3'

services:
  postgre:
    image: postgres
    container_name: postgre
    environment:
       POSTGRES_PASSWORD: Passw0rd!
       POSTGRES_USER: postgres
       POSTGRES_DB: template_db
    ports:
      - 5432:5432
    volumes:
      - postgres-template-data:/var/lib/postgresql/data
    networks:
      - app-network

  redisdb:
    image: redis:6.2-alpine
    restart: always
    container_name: redisdb
    environment:
        REDIS_PASSWORD: Unravel!
    command: redis-server --save 20 1 --loglevel warning --requirepass Unravel!
    ports:
      - "6379:6379"
    volumes:
      - ./myredis/conf:/usr/local/etc/redis
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: core-message-broker
    environment:
        - RABBITMQ_DEFAULT_USER=Unravel
        - RABBITMQ_DEFAULT_PASS=Unr4vel!
    restart: on-failure
    ports:
        - "5672:5672"
        - "15672:15672"
    networks:
        - app-network
    volumes:
        - "rabbitmq-volume:/etc/rabbitmq/rabbitmq-volume"


networks:
  app-network:
    driver: bridge

volumes:
  postgres-template-data:
  rabbitmq-volume:  